[project]
name = "jupyter-multi-env"
version = "0.1.0"
channels = ["conda-forge", "pytorch"]
platforms = ["win-64","linux-64"]

[dependencies]
python = "3.12.*"
jupyter = "*"
jupyterlab = "*"
python-dotenv = "*"
zeroc-ice = "==3.6.5"
omero-py = "*"
ipykernel = "*"

[pypi-dependencies]
ezomero = ">=3.2.0"
pixi-kernel = "*"
jupyter-remote-desktop-proxy = "*"  # This replaces your custom VNC setup
opencv-contrib-python = "*"

[feature.microsam.dependencies]
micro_sam = ">=1.6.0,<2"
napari = "*"
napari-omero = "*"

[feature.cellpose.dependencies]
cellpose = ">=4.0.6, <5"

[feature.gui.dependencies]
qt-main = "*"
pyqt = "*"

[environments]
default = { features = ["gui"] }
microsam = { features = ["microsam", "gui"] }
cellpose = { features = ["cellpose", "gui"] }
full = { features = ["microsam", "cellpose", "gui"] }