[workspace]
authors = ["Maarten Paul <maarten.paul@gmail.com>"]
channels = ["conda-forge"]
name = "upload"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
zeroc-ice = ">=3.6.5,<4"
jupyterlab = ">=4.4.6,<5"

[pypi-dependencies]
ezomero = ">=3.2.1, <4"
dotenv = ">=0.9.9, <0.10"
