name: documentation
on:
  push:
    branches:
      - main  # or master, depending on your default branch
  pull_request:
    branches:
      - main  # or master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs gh-deploy --force